---

- name: run apt-update on all nodes
  hosts: vms
  become: true
  tasks:
    - name: apt update
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 # one day
        autoremove: yes
